apiVersion: v1
kind: Pod
metadata:
  name: pnc-load-test
  namespace: default
  labels:
    app: pnc-load-test
spec:
  containers:
    - name: pnc-load-test
      image: itspeetah/np-pnc-load:dev
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      ports:
        - containerPort: 8089
          name: http
  restartPolicy: Always
