apiVersion: neptuneplus.polimi.it/v1alpha1
kind: DependencyGraph
metadata:
  labels:
    app.kubernetes.io/name: cepdag-controller
    app.kubernetes.io/managed-by: kustomize
  name: depdag-pnc-sequential
  namespace: openfaas-fn
spec:
  nodes:
    - functionName: pnc-seq-deps
      functionNamespace: openfaas-fn
      nominalLocalResponseTime: 10m
      invocations:
        - functionName: prime-numbers-invoked-0
          functionNamespace: openfaas-fn
          edgeId: 1
          edgeMultiplier: 1
    - functionName: prime-numbers-invoked-0
      functionNamespace: openfaas-fn
      nominalLocalResponseTime: 100m
      invocations: []
