resources:
  - allocation-algorithm.yaml
  - metrics-exposer.yaml
  - cpu-monitoring.yaml
  - monitoring.yaml
  - slpa.yaml
  - delay.yaml
  - pod-autoscaler.yaml
  - system-controller.yaml
  - dispatcher.yaml
  - podscale-controller.yaml
  - timescale-db.yaml
  - example-cs.yaml
  # - prime-numbers-function.yaml
