apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: pnc-con-nodeps
  namespace: openfaas-fn
spec:
  image: itspeetah/np-prime-numbers-caller:dev
  labels:
    com.openfaas.scale.factor: "20"
    com.openfaas.scale.max: "100"
    com.openfaas.scale.min: "1"
    com.openfaas.scale.zero: "false"
    edgeautoscaler.polimi.it/scheduler: edge-autoscaler
  name: pnc-con-nodeps
  readOnlyRootFilesystem: false
  limits:
    cpu: "200m"
    memory: "1000Mi"
  requests:
    cpu: "30m"
    memory: "1000Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: pnc-con-nodeps
  labels:
    name: pnc-con-nodeps
  namespace: openfaas-fn
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    edgeautoscaler.polimi.it/function-name: "pnc-con-nodeps"
    edgeautoscaler.polimi.it/function-namespace: "openfaas-fn"
