apiVersion: neptuneplus.polimi.it/v1alpha1
kind: DependencyGraph
metadata:
  labels:
    app.kubernetes.io/name: cepdag-controller
    app.kubernetes.io/managed-by: kustomize
  name: prime-numbers-caller-sequential
  namespace: openfaas-fn
spec:
  nodes:
    - functionName: prime-numbers-caller-withdeps
      functionNamespace: openfaas-fn
      nominalLocalResponseTime: 25m
      invocations:
        - functionName: prime-numbers-invoked-0
          functionNamespace: openfaas-fn
          edgeId: 1
          edgeMultiplier: 1
        - functionName: prime-numbers-invoked-1
          functionNamespace: openfaas-fn
          edgeId: 1
          edgeMultiplier: 1
    - functionName: prime-numbers-invoked-0
      functionNamespace: openfaas-fn
      nominalLocalResponseTime: 15m
      invocations: []
    - functionName: prime-numbers-invoked-1
      functionNamespace: openfaas-fn
      nominalLocalResponseTime: 15m
      invocations: []
