apiVersion: neptuneplus.polimi.it/v1alpha1
kind: DependencyGraph
metadata:
  labels:
    app.kubernetes.io/name: cepdag-controller
    app.kubernetes.io/managed-by: kustomize
  name: prime-numbers-caller-sequential
  namespace: openfaas-fn
spec:
  nodes:
    - functionName: pnc-seq-deps
      functionNamespace: openfaas-fn
      nominalLocalResponseTime: 10m
      invocations:
        - functionName: prime-numbers-invoked-0
          functionNamespace: openfaas-fn
          edgeId: 1
          edgeMultiplier: 1
        - functionName: prime-numbers-invoked-1
          functionNamespace: openfaas-fn
          edgeId: 2
          edgeMultiplier: 1
        - functionName: prime-numbers-invoked-2
          functionNamespace: openfaas-fn
          edgeId: 3
          edgeMultiplier: 1
        - functionName: prime-numbers-invoked-3
          functionNamespace: openfaas-fn
          edgeId: 4
          edgeMultiplier: 1
        - functionName: prime-numbers-invoked-4
          functionNamespace: openfaas-fn
          edgeId: 5
          edgeMultiplier: 1
    - functionName: prime-numbers-invoked-0
      functionNamespace: openfaas-fn
      nominalLocalResponseTime: 100m
      invocations: []
    - functionName: prime-numbers-invoked-1
      functionNamespace: openfaas-fn
      nominalLocalResponseTime: 100m
      invocations: []
    - functionName: prime-numbers-invoked-2
      functionNamespace: openfaas-fn
      nominalLocalResponseTime: 100m
      invocations: []
    - functionName: prime-numbers-invoked-3
      functionNamespace: openfaas-fn
      nominalLocalResponseTime: 100m
      invocations: []
    - functionName: prime-numbers-invoked-4
      functionNamespace: openfaas-fn
      nominalLocalResponseTime: 100m
      invocations: []
