resources:
  # Dag
  - dags/dag-concurrent-2.yaml
  # Entrypoints
  - entrypoint-functions/caller-dep-fn.yaml
  - entrypoint-functions/caller-nodep-fn.yaml
  # Invoked
  - invoked-functions/prime-numbers-invoked-0.yaml
  - invoked-functions/prime-numbers-invoked-1.yaml
